apiVersion: apps/v1
kind: Deployment
metadata:
  name: area-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: area-database
  template:
    metadata:
      labels:
        app: area-database
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: backend-env
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
          subPath: postgres
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc