apiVersion: v1
kind: Secret
metadata:
  name: dockercred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoibWFkYWFnYWluIiwicGFzc3dvcmQiOiJnaHBfZ25SeXowa3JZcllWYkVWVHNxTFhIVFFabWVNamltMjlDV1VuIiwiZW1haWwiOiJhZGFtLnplcnJvdWtAZXBpdGVjaC5ldSIsImF1dGgiOiJCQVNFNjRfRU5DT0RFRF9BVVRIIn19fQ==