name: Build and Push Docker Images

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        # password: ${{ secrets.GITHUB_TOKEN }}
        password: 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
    - name: Build and push database image
      uses: docker/build-push-action@v2
      with:
        context: ./AREA/Backend/Database
        push: true
        tags: ghcr.io/mirror-area/area-database:latest
    - name: Build and push monitoring image
      uses: docker/build-push-action@v2
      with:
        context: ./AREA/Backend/Monitoring
        push: true
        tags: ghcr.io/mirror-area/area-monitoring:latest
    - name: Build and push frontend image
      uses: docker/build-push-action@v2
      with:
        context: ./AREA/Frontend/FrontWeb
        push: true
        tags: ghcr.io/mirror-area/area-frontend:latest

    # - name: Build and push gateway image
      # uses: docker/build-push-action@v2
      # with:
        # context: ./AREA/Backend/Gateway
        # push: true
        # tags: ghcr.io/epitechpromo2027/area-gateway:latest