name: Build and Push Docker Images
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.ALEXIS_SECRET }}

    - name: Decode Database .env file
      run: cat ./AREA/Backend/Database/.env.encoded | base64 -d > ./AREA/Backend/Database/.env

    - name: Build and push Database image service
      uses: docker/build-push-action@v2
      with:
        context: ./AREA/Backend/Database
        file: ./AREA/Backend/Database/Dockerfile
        push: true
        tags: ghcr.io/epitechpromo2027/area-database:latest

    - name: Build and push frontend image
      uses: docker/build-push-action@v2
      with:
        context: ./AREA/Frontend/FrontWeb
        file: ./AREA/Frontend/FrontWeb/Dockerfile
        push: true
        tags: ghcr.io/epitechpromo2027/area-frontend:latest

    - name: Decode Monitoring .env file
      run: cat ./AREA/Backend/Monitoring/.env.encoded | base64 -d > ./AREA/Backend/Monitoring/.env

    - name: Build and push monitoring service image
      uses: docker/build-push-action@v2
      with:
        context: ./AREA/Backend/Monitoring
        file: ./AREA/Backend/Monitoring/Dockerfile
        push: true
        tags: ghcr.io/epitechpromo2027/area-monitoring:latest